### PR TITLE
Fix Manjaro missing `make`; add Pop! OS "jammy", Linux Mint 21.1 "vera", and Funtoo

### LINKED ISSUE #35: Support Pop! OS directly
**Is your feature request related to a problem? Please describe.**
Some of our users run Pop! OS. We do not directly support that Linux distribution yet.

**Describe the solution you'd like**
It would be nice if we added direct support for Pop! OS.

**Describe alternatives you've considered**
Continue to refer Pop! OS users to the corresponding Ubuntu packages?

**Additional context**
Brought up by @BenjamenMeyer in [this comment](https://github.com/vegastrike/Vega-Strike-Engine-Source/discussions/750#discussioncomment-4374973)

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to Vega Strike's Build System Docker Images.

Please answer the following:

Code Changes:
- [X] CI Change

Issues:
- Please list any related issues
- Closes #35 

Purpose:
- What is this pull request trying to do? Add a few more Linux distros, plus fix a problem with the Manjaro bootstrapping process
- What release is this for? N/A
- Is there a project or milestone we should apply this to? N/A

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Could you try running this version of the bootstrap script on Pop! OS, and see if it works? Thanks

**Comment by stephengtuggy** [comment]
Note that I was not able to find a recent build of Pop! OS on Docker Hub.

**Comment by stephengtuggy** [comment]
I answered my own question: It works on Pop! OS. Merging.

**Comment by BenjamenMeyer** [comment]
Yeah, PopOS doesn't seem to provide their own docker images, and the only ones I could find were for 20.04 so any support for PopOS will really be left to the developer and building on their own system.

**Pull request merged**
