### PR TITLE
Enhancement: SDL2 support

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Vega Strike is moving to use SDL2. Add support to the docker images for SDL2 in addition to SDL1.

- add a tool to easily check that the script works locally
- ignore Vi Swap files

Thank you for submitting a pull request and becoming a contributor to Vega Strike's Build System Docker Images.

Please answer the following:

Code Changes:
- [ ] This is a documentation change only
- [x] CI Change

Issues:
- [VS Engine SDL2 Support](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/792)

Purpose:
- What is this pull request trying to do? Adds SDL2 Dev libraries
- What release is this for? Adding SDL2 support
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
NOTE: We already removed Kinetic from the VS Engine repo.

**Comment by royfalk** [comment]
Looks fine to me. I did remember that I needed to touch this repo as well but wasn't sure when to do it (before or after) we merge the main PR. 
One comment - should we keep sdl1.2?

**Review by royfalk — APPROVED** [review]
Other than my comment about SDL1.2, it looks fine.

**Comment by BenjamenMeyer** [comment]
Keeping the SDL 1.x for now. We still have releases that use it . We can clean that up after 0.9.x gets released

**Pull request merged**
